"""add table cities + rell with another tables

Revision ID: 95cce87fe4c2
Revises: 4b1d52c7dd4f
Create Date: 2025-01-29 14:01:39.395467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '95cce87fe4c2'
down_revision: Union[str, None] = '4b1d52c7dd4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('authors', sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('authors', sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('authors', sa.Column('city_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'authors', 'cities', ['city_id'], ['id'])
    op.drop_column('authors', 'city')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'authors', type_='foreignkey')
    op.drop_column('authors', 'city_id')
    op.drop_column('authors', 'last_name')
    op.drop_column('authors', 'first_name')
    op.drop_table('cities')
    # ### end Alembic commands ###
